language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davideimola/fibonacci-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davideimola/fibonacci-dev npm run test

after_success:
  - docker build -t davideimola/fibonacci ./client
  - docker build -t davideimola/fibonacci-nginx ./nginx
  - docker build -t davideimola/fibonacci-server ./server
  - docker build -t davideimola/fibonacci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push davideimola/fibonacci
  - docker push davideimola/fibonacci-nginx
  - docker push davideimola/fibonacci-server
  - docker push davideimola/fibonacci-worker